django/hub/accounts/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.AccountListView.as_view(), name='account_list'),
    url(
        r'^organogram/$',
        views.OrganogramView.as_view(),
        name='organogram'
    ),
    url(
        r'^(?P<slug>.*)/update/$',
        views.AccountUpdateView.as_view(),
        name='account_update'
    ),
    url(
        r'^(?P<slug>.*)/add-award/$',
        views.AccountAwardCreateView.as_view(),
        name='account_award_add'
    ),
    url(
        r'^(?P<slug>.*)/$',
        views.AccountDetailView.as_view(),
        name='account_detail'
    )
)

django/hub/pr/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url('^$', views.PressReleaseListView.as_view(), name='pressrelease_list'),
    url(
        '^(?P<pk>\d+)/$',
        views.PressReleaseDetailView.as_view(),
        name='pressrelease_detail'
    ),
    url(
        '^(?P<pk>\d+)/update/$',
        views.PressReleaseUpdateView.as_view(),
        name='pressrelease_update'
    ),
    url(
        '^(?P<pressrelease_id>\d+)/faq/add/$',
        views.QuestionCreateView.as_view(),
        name='pressrelease_question_add'
    ),
    url(
        '^(?P<pressrelease_id>\d+)/faq/(?P<pk>\d+)/$',
        views.QuestionUpdateView.as_view(),
        name='pressrelease_question_update'
    ),
    url(
        '^add/$',
        views.PressReleaseCreateView.as_view(),
        name='pressrelease_add'
    ),
)

django/hub/teams/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.TeamListView.as_view(), name='team_list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
    url(r'^add/$', views.TeamCreateView.as_view(), name='team_create'),
)

django/hub/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from news.models import Entry


admin.autodiscover()


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['news_entries'] = Entry.objects.order_by('-created_at')
        return context


class ProjectsRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return '/products/{}'.format(self.kwargs.get('pattern', ''))


urlpatterns = patterns(
    '',
    url('^$', HomeView.as_view(), name='home'),
    url(r'^login/$', TemplateView.as_view(template_name='login.html')),
    url(r'^mgr/', include(admin.site.urls)),
    url(r'^projects/(?P<pattern>.*?)$', ProjectsRedirectView.as_view()),

    # third party
    (r'^accounts/', include('allauth.urls')),

    # local apps
    (r'^pr/', include('pr.urls', namespace='pr')),
    (r'^people/', include('accounts.urls', namespace='accounts')),
    (r'^teams/', include('teams.urls', namespace='teams')),
    (r'^products/', include('projects.urls', namespace='projects')),
    (r'^', include('core.urls', namespace='core')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/hub/pr/models.py
# coding: utf-8
import logging
from django.db import models
from django.utils.timezone import now
from accounts.models import Account
from teams.models import Team
from utils.softdelete import SoftDeleteMixin


logger = logging.getLogger('pr.models')


class PressRelease(models.Model, SoftDeleteMixin):
    added_by = models.ForeignKey(Account, related_name='added_releases')
    title = models.CharField(u'título', max_length=64)
    author_name = models.CharField(u'nome do autor', max_length=32)
    author_email = models.EmailField(u'e-mail do autor')
    text = models.TextField(u'texto')

    teams = models.ManyToManyField(Team, verbose_name=u'times envolvidos')

    created_at = models.DateTimeField(default=now)

    def __unicode__(self):
        return self.title


class Question(models.Model, SoftDeleteMixin):
    author = models.ForeignKey(Account, related_name='questions')
    press_release = models.ForeignKey(PressRelease)
    question = models.TextField(u'pergunta')
    answer = models.TextField(
        u'resposta', blank=True,
        help_text=u'Não sabe a resposta ainda? Deixe em branco e alguém responderá')
    created_at = models.DateTimeField(default=now)

django/hub/pr/forms.py
# coding: utf-8

from django import forms

from .models import PressRelease, Question


class PressReleaseForm(forms.ModelForm):

    class Meta:
        model = PressRelease
        exclude = ('added_by', 'created_at')


class AddQuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('question', 'answer')


class QuestionUpdateForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('question', 'answer')

django/hub/pr/views.py
# coding: utf-8
import logging

from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import AddQuestionForm, PressReleaseForm, QuestionUpdateForm
from .models import PressRelease, Question

logger = logging.getLogger('pr.views')


class PressReleaseListView(ListView):
    queryset = PressRelease.objects.order_by('-created_at')
    template_name = 'pr/pressrelease_list.html'


class PressReleaseDetailView(DetailView):
    queryset = PressRelease.objects.all()
    template_name = 'pr/pressrelease_detail.html'


class PressReleaseCreateView(CreateView):
    form_class = PressReleaseForm
    template_name = 'pr/pressrelease_add.html'
    success_url = reverse_lazy('pr:pressrelease_list')

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super(PressReleaseCreateView, self).form_valid(form)


class PressReleaseUpdateView(UpdateView):
    model = PressRelease
    form_class = PressReleaseForm
    template_name = 'pr/pressrelease_update.html'

    def dispatch(self, request, *args, **kwargs):
        press_release = self.get_object()

        is_superuser = request.user.is_superuser
        is_owner = request.user.id == press_release.added_by_id

        if not is_superuser and not is_owner:
            return HttpResponseForbidden(u'Você não pode editar esse item')

        return super(PressReleaseUpdateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse(
            'pr:pressrelease_detail',
            kwargs={'pk': self.object.id}
        )


class QuestionCreateView(CreateView):
    form_class = AddQuestionForm
    template_name = 'pr/question_add.html'

    def get(self, *args, **kwargs):
        self.press_release = PressRelease.objects.get(
            pk=kwargs['pressrelease_id'],
        )
        return super(QuestionCreateView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        self.press_release = PressRelease.objects.get(
            pk=kwargs['pressrelease_id'],
        )
        return super(QuestionCreateView, self).post(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuestionCreateView, self).get_context_data(**kwargs)
        context['press_release'] = self.press_release
        return context

    def form_valid(self, form):
        question = form.save(commit=False)
        question.press_release = self.press_release
        question.author = self.request.user
        question.save()

        return HttpResponseRedirect(
            reverse('pr:pressrelease_detail', kwargs={'pk': question.press_release.id})
        )


class QuestionUpdateView(UpdateView):
    model = Question
    form_class = QuestionUpdateForm
    template_name = 'pr/question_update.html'

    def get_success_url(self):
        return reverse(
            'pr:pressrelease_detail',
            kwargs={'pk': self.get_object().press_release.id}
        )

django/hub/pr/templates/pr/pressrelease_add.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}pr{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Adicionar press release</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

django/hub/pr/templates/pr/pressrelease_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block tab_name %}pr{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <div class="clearfix content-heading media">
                <h2>
                    {{ object.title }}

                    {% if request.user.is_superuser or request.user.id == object.added_by.id %}
                    <small>
                        <a href="{% url 'pr:pressrelease_update' object.pk %}">Editar</a>
                    </small>
                    {% endif %}
                </h2>

                <p class="text-muted">
                    {{ object.author_name }} (<i>{{ object.author_email }}</i>)
                </p>

                <p>
                    <span class="glyphicon glyphicon-time"></span>
                        {{ object.created_at|date:"d/m/Y \à\s H:i" }}
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            {{ object.text|linebreaksbr }}
        </div>
    </div>

    <hr>

    <div class="faq-box">
        <h3>
            FAQ
            <a class="btn btn-sm btn-default" href="{% url 'pr:pressrelease_question_add' object.id %}"><i class="glyphicon glyphicon-pencil"></i> Adicionar pergunta</a>
        </h3>

        {% for question in object.question_set.all %}
            <div class="row pr-faq-question">
                <div class="col-md-10">
                    <p class="question">
                        {{ question.question }}
                        <i class="text-muted pr-faq-question-author">(por <a href="{% url 'accounts:account_detail' question.author.email %}">{{ question.author.name }}</a>)</i>

                    </p>
                    <div class="answer">
                        {% if question.answer %}
                            {{ question.answer|linebreaks }}
                        {% else %}
                            <a class="btn btn-sm btn-default" href="{% url 'pr:pressrelease_question_update' pressrelease_id=object.id pk=question.id %}"><i class="glyphicon glyphicon-pencil"></i> Responder</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        {% empty %}
            Nenhuma pergunta por enquanto...
        {% endfor %}
        </div>


{% endblock content %}

django/hub/pr/templates/pr/pressrelease_list.html
{% extends "base.html" %}

{% block tab_name %}pr{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
        <h2>Press releases</h2>
        </div>

        <div class="col-md-2">
            <a class="btn btn-default" href="{% url 'pr:pressrelease_add' %}"><i class="glyphicon glyphicon-plus"></i> Novo press release</a>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-md-10">
            {% for press_release in object_list %}
                <h3>
                    <a href="{% url 'pr:pressrelease_detail' press_release.id %}">{{ press_release.title }}</a>
                </h3>

                <p><span class="glyphicon glyphicon-time"></span> {{ press_release.created_at|date:"d/m/Y \à\s H:i" }}</p>


                {% with press_release.teams.all as teams %}
                    {% if teams %}
                        <div>
                            <p>
                                {% for team in teams %}
                                    <a href="{% url 'teams:team_detail' team.id %}" class="btn btn-default"><i class="glyphicon glyphicon-user"></i> {{ team.name }}</a>
                                {% endfor %}
                            </p>
                        </div>
                    {% endif %}
                {% endwith %}

                <hr>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

django/hub/pr/templates/pr/pressrelease_update.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}pr{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Editar press release</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

django/hub/pr/templates/pr/question_add.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}pr{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>FAQ: {{ press_release.title }}</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

django/hub/pr/templates/pr/question_update.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>FAQ: {{ object.press_release.title }}</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>

            </form>
        </div>
    </div>

{% endblock %}