django/hub/accounts/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.AccountListView.as_view(), name='account_list'),
    url(
        r'^organogram/$',
        views.OrganogramView.as_view(),
        name='organogram'
    ),
    url(
        r'^(?P<slug>.*)/update/$',
        views.AccountUpdateView.as_view(),
        name='account_update'
    ),
    url(
        r'^(?P<slug>.*)/add-award/$',
        views.AccountAwardCreateView.as_view(),
        name='account_award_add'
    ),
    url(
        r'^(?P<slug>.*)/$',
        views.AccountDetailView.as_view(),
        name='account_detail'
    )
)

django/hub/pr/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url('^$', views.PressReleaseListView.as_view(), name='pressrelease_list'),
    url(
        '^(?P<pk>\d+)/$',
        views.PressReleaseDetailView.as_view(),
        name='pressrelease_detail'
    ),
    url(
        '^(?P<pk>\d+)/update/$',
        views.PressReleaseUpdateView.as_view(),
        name='pressrelease_update'
    ),
    url(
        '^(?P<pressrelease_id>\d+)/faq/add/$',
        views.QuestionCreateView.as_view(),
        name='pressrelease_question_add'
    ),
    url(
        '^(?P<pressrelease_id>\d+)/faq/(?P<pk>\d+)/$',
        views.QuestionUpdateView.as_view(),
        name='pressrelease_question_update'
    ),
    url(
        '^add/$',
        views.PressReleaseCreateView.as_view(),
        name='pressrelease_add'
    ),
)

django/hub/projects/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^add/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^(?P<project_pk>\d+)/applications/add/$',
        views.ProjectCreateView.as_view(),
        name='child_project_create'),
    url(r'^(?P<pk>\d+)/$',
        views.ProjectDetailView.as_view(),
        name='project_detail'),
    url(
        r'^(?P<pk>\d+)/update/$',
        views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(
        r'^(?P<project_id>\d+)/changelog/add/$',
        views.ChangelogCreateView.as_view(),
        name='changelog_add'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/update/$',
        views.ChangelogUpdateView.as_view(),
        name='changelog_update'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/delete/$',
        views.ChangelogDeleteView.as_view(),
        name='changelog_delete'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_mail/$',
        views.ChangelogSendMailView.as_view(),
        name='changelog_send_mail'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_slack/$',
        views.ChangelogSendSlackView.as_view(),
        name='changelog_send_slack'
    ),
)

django/hub/teams/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.TeamListView.as_view(), name='team_list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
    url(r'^add/$', views.TeamCreateView.as_view(), name='team_create'),
)

django/hub/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from news.models import Entry


admin.autodiscover()


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['news_entries'] = Entry.objects.order_by('-created_at')
        return context


class ProjectsRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return '/products/{}'.format(self.kwargs.get('pattern', ''))


urlpatterns = patterns(
    '',
    url('^$', HomeView.as_view(), name='home'),
    url(r'^login/$', TemplateView.as_view(template_name='login.html')),
    url(r'^mgr/', include(admin.site.urls)),
    url(r'^projects/(?P<pattern>.*?)$', ProjectsRedirectView.as_view()),

    # third party
    (r'^accounts/', include('allauth.urls')),

    # local apps
    (r'^pr/', include('pr.urls', namespace='pr')),
    (r'^people/', include('accounts.urls', namespace='accounts')),
    (r'^teams/', include('teams.urls', namespace='teams')),
    (r'^products/', include('projects.urls', namespace='projects')),
    (r'^', include('core.urls', namespace='core')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/hub/pr/models.py
# coding: utf-8
import logging
from django.db import models
from django.utils.timezone import now
from accounts.models import Account
from teams.models import Team
from utils.softdelete import SoftDeleteMixin


logger = logging.getLogger('pr.models')


class PressRelease(models.Model, SoftDeleteMixin):
    added_by = models.ForeignKey(Account, related_name='added_releases')
    title = models.CharField(u'título', max_length=64)
    author_name = models.CharField(u'nome do autor', max_length=32)
    author_email = models.EmailField(u'e-mail do autor')
    text = models.TextField(u'texto')

    teams = models.ManyToManyField(Team, verbose_name=u'times envolvidos')

    created_at = models.DateTimeField(default=now)

    def __unicode__(self):
        return self.title


class Question(models.Model, SoftDeleteMixin):
    author = models.ForeignKey(Account, related_name='questions')
    press_release = models.ForeignKey(PressRelease)
    question = models.TextField(u'pergunta')
    answer = models.TextField(
        u'resposta', blank=True,
        help_text=u'Não sabe a resposta ainda? Deixe em branco e alguém responderá')
    created_at = models.DateTimeField(default=now)

django/hub/teams/models.py
# coding: utf-8
import logging
from django.db import models
from utils.softdelete import SoftDeleteMixin


logger = logging.getLogger('teams.models')


class Area(models.Model, SoftDeleteMixin):
    leader = models.ForeignKey('accounts.Account', related_name='area_set',
                               verbose_name=u'líder da área')
    name = models.CharField(u'nome', max_length=64)

    def __unicode__(self):
        return self.name


class Team(models.Model, SoftDeleteMixin):
    area = models.ForeignKey(Area, verbose_name=u'área')
    leader = models.ForeignKey('accounts.Account', related_name='team_set',
                               verbose_name=u'líder do time')
    name = models.CharField(u'nome', max_length=64)

    image = models.ImageField(
        u'foto', upload_to='teams/', blank=True,
        help_text=u'Tire uma foto do seu time! Envie imagens quadradas (~500x500px)',
    )

    class Meta:
        ordering = ('area', 'name')

    def __unicode__(self):
        return u'{} - {}'.format(self.area, self.name)

django/hub/teams/forms.py
# coding: utf-8
from django import forms
from models import Team


class TeamCreateForm(forms.ModelForm):

    class Meta:
        model = Team


class TeamUpdateForm(forms.ModelForm):

    class Meta:
        model = Team

django/hub/teams/views.py
# coding: utf-8
import logging
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from forms import TeamCreateForm, TeamUpdateForm
from models import Team


logger = logging.getLogger('teams.views')


class TeamListView(ListView):
    # order is important (using ttag `ifchanged`)
    queryset = Team.objects.order_by('area__name', 'name')
    template_name = 'teams/team_list.html'


class TeamDetailView(DetailView):
    queryset = Team.objects.all()
    template_name = 'teams/team_detail.html'


class TeamUpdateView(UpdateView):
    form_class = TeamUpdateForm
    queryset = Team.objects.all()
    template_name = 'teams/team_update.html'
    success_url = reverse_lazy('teams:team_list')

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return Team.objects.all()
        return Team.objects.filter(id=self.request.user.team_id)


class TeamCreateView(CreateView):
    admin_required = True
    form_class = TeamCreateForm
    template_name = 'teams/team_create.html'
    success_url = reverse_lazy('teams:team_list')

django/hub/teams/templates/teams/team_create.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}teams{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Adicionar time</h2>
            <hr>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

django/hub/teams/templates/teams/team_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block tab_name %}teams{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <div class="clearfix content-heading media">
                {% if team.image %}
                    <img height="70" width="70" src="{{ team.image|thumbnail_url:'project' }}" class="img-circle pull-left">
                {% endif %}

                <h2>
                    {{ team.name }}

                    {% if user in team.account_set.all or user.is_superuser %}
                        <a class="btn btn-sm btn-default" href="{% url 'teams:team_update' team.id %}"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                    {% endif %}
                </h2>
            </div>
        </div>
    </div>
    <hr>


    <div class="row">
        <div class="col-md-10">
            <h3>Equipe</h3>

            <table class="table">
                <thead>
                    <tr>
                        <th class="col-md-4">Nome</th>
                        <th class="col-md-3">E-mail</th>
                        <th class="col-md-3">Filial</th>
                        <th class="col-md-2">Telefone</th>
                    </tr>
                </thead>

                {% if team.leader %}
                    <tr>
                        <td><img height="25" width="25" src="{{ team.leader.image|thumbnail_url:'person' }}" class="img-circle"> <a href="{% url 'accounts:account_detail' team.leader.email %}">{{ team.leader.name }}</a></td>
                        <td>{{ team.leader.email }}</td>
                        <td>{{ team.leader.branch }}</td>
                        <td>{{ team.leader.phone }}</td>
                    </tr>
                {% endif %}

                {% for account in object.account_set.all %}
                    {% if not account.id == team.leader.id %}
                        <tr>
                            <td><img height="25" width="25" src="{{ account.image|thumbnail_url:'person' }}" class="img-circle"> <a href="{% url 'accounts:account_detail' account.email %}">{{ account.name }}</a></td>
                            <td>{{ account.email }}</td>
                            <td>{{ account.branch }}</td>
                            <td>{{ account.phone }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}

            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3>Projetos</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-md-2">Nome</th>
                        <th class="col-md-8">Headline</th>
                    </tr>
                </thead>

                {% for project in object.project_set.all %}
                    <tr>
                        <td><a href="{% url 'projects:project_detail' project.id %}">{{ project.name }}</a></td>
                        <td>{{ project.headline }}</td>
                    </tr>
                {% endfor %}

            </table>
        </div>
    </div>


    {% with object.pressrelease_set.all as releases %}
        {% if releases %}
            <div class="row">
                <div class="col-md-10">
                    <h3>Press releases</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-md-2">Autor</th>
                                <th class="col-md-10">Título</th>
                            </tr>
                        </thead>

                        {% for press_release in releases %}
                            <tr>
                                <td>{{ press_release.author_name }}</td>
                                <td><a href="{% url 'pr:pressrelease_detail' press_release.id  %}">{{ press_release.title }}</a></td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        {% endif %}
    {% endwith %}

{% endblock content %}

django/hub/teams/templates/teams/team_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block tab_name %}teams{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Times</h2>
        </div>

        {% if user.is_superuser %}
            <div class="col-md-2">
                <a class="btn btn-default" href="{% url 'teams:team_create' %}"><i class="glyphicon glyphicon-plus"></i> Novo time</a>
            </div>
        {% endif %}
    </div>
    <hr>


    {% for team in object_list %}
        {% ifchanged team.area %}
            {% if not forloop.first %}
                </div>
                <hr>
            {% endif %}
            <h3>{{ team.area.name }}</h3>

            <div class="row">
        {% endifchanged %}

        <div class="col-md-4">
            <div class="team">
                <div class="row">
                    <div class="col-md-3 project-image">
                        {% if team.image %}
                            <img height="90" width="90" src="{{ team.image|thumbnail_url:'project' }}" class="img-circle img-responsive">
                        {% else %}
                            <img height="90" width="90" src="{{ STATIC_URL }}img/noimage90.png" class="img-circle img-responsive">
                        {% endif %}
                    </div>
                    <div class="col-md-9">
                        <h3>
                            <a href="{% url 'teams:team_detail' team.id %}">{{ team.name }}</a>
                        </h3>
                        <ul>
                            {% for member in team.account_set.all %}
                                <li>{{ member.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        {% if forloop.last %}
            </div>
        {% endif %}
    {% endfor %}



{% endblock %}

django/hub/teams/templates/teams/team_update.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}teams{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Atualizar time: {{ object }}</h2>
        </div>
    </div>
    <hr>


    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}