django/hub/accounts/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.AccountListView.as_view(), name='account_list'),
    url(
        r'^organogram/$',
        views.OrganogramView.as_view(),
        name='organogram'
    ),
    url(
        r'^(?P<slug>.*)/update/$',
        views.AccountUpdateView.as_view(),
        name='account_update'
    ),
    url(
        r'^(?P<slug>.*)/add-award/$',
        views.AccountAwardCreateView.as_view(),
        name='account_award_add'
    ),
    url(
        r'^(?P<slug>.*)/$',
        views.AccountDetailView.as_view(),
        name='account_detail'
    )
)

django/hub/core/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^tags/(?P<tag_id>\d+)/$', views.TagsListView.as_view(), name='tags_list'),
    url(r'^get_tags_json/$', views.get_tags_json, name='get_tags_json'),
)

django/hub/projects/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^add/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^(?P<project_pk>\d+)/applications/add/$',
        views.ProjectCreateView.as_view(),
        name='child_project_create'),
    url(r'^(?P<pk>\d+)/$',
        views.ProjectDetailView.as_view(),
        name='project_detail'),
    url(
        r'^(?P<pk>\d+)/update/$',
        views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(
        r'^(?P<project_id>\d+)/changelog/add/$',
        views.ChangelogCreateView.as_view(),
        name='changelog_add'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/update/$',
        views.ChangelogUpdateView.as_view(),
        name='changelog_update'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/delete/$',
        views.ChangelogDeleteView.as_view(),
        name='changelog_delete'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_mail/$',
        views.ChangelogSendMailView.as_view(),
        name='changelog_send_mail'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_slack/$',
        views.ChangelogSendSlackView.as_view(),
        name='changelog_send_slack'
    ),
)

django/hub/teams/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.TeamListView.as_view(), name='team_list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
    url(r'^add/$', views.TeamCreateView.as_view(), name='team_create'),
)

django/hub/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from news.models import Entry


admin.autodiscover()


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['news_entries'] = Entry.objects.order_by('-created_at')
        return context


class ProjectsRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return '/products/{}'.format(self.kwargs.get('pattern', ''))


urlpatterns = patterns(
    '',
    url('^$', HomeView.as_view(), name='home'),
    url(r'^login/$', TemplateView.as_view(template_name='login.html')),
    url(r'^mgr/', include(admin.site.urls)),
    url(r'^projects/(?P<pattern>.*?)$', ProjectsRedirectView.as_view()),

    # third party
    (r'^accounts/', include('allauth.urls')),

    # local apps
    (r'^pr/', include('pr.urls', namespace='pr')),
    (r'^people/', include('accounts.urls', namespace='accounts')),
    (r'^teams/', include('teams.urls', namespace='teams')),
    (r'^products/', include('projects.urls', namespace='projects')),
    (r'^', include('core.urls', namespace='core')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/hub/projects/forms.py
# coding: utf-8

from django import forms

from models import Changelog, Project
from utils.cleantags import CleanTagsMixin
from utils.validators import validate_email_list


class ProjectForm(CleanTagsMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        qs = Project.objects.filter(parent=None)
        self.fields['parent'].queryset = qs

        if self.instance:
            self.fields['parent'].queryset = qs.exclude(pk=self.instance.pk)

        if self.instance.parent or self.initial.get('parent'):
            self.fields['parent'].widget = forms.HiddenInput()

    class Meta:
        model = Project
        exclude = ('added_by', 'created_at')


class ChangelogForm(forms.ModelForm):
    email_recipients = forms.CharField(
        label=u'Destinatários',
        required=False,
        widget=forms.Textarea,
        validators=[validate_email_list]
    )
    send_mail = forms.BooleanField(label=u'Enviar e-mail', required=False)

    class Meta:
        model = Changelog
        fields = ('send_mail', 'email_recipients', 'email_subject',
                  'description')


class SendMailChangelogForm(forms.ModelForm):
    email_recipients = forms.CharField(
        label=u'Destinatários',
        required=False,
        widget=forms.Textarea,
        validators=[validate_email_list]
    )

    class Meta:
        model = Changelog
        fields = ('email_recipients', 'email_subject')


class SendSlackForm(forms.Form):
    channel = forms.CharField(
        label=u'Canal',
        help_text=u'Iniciar nome de canal com #, usuários com @, '
                  u'se enviar para múltiplos canais ou usuários, separá-los '
                  u'por vírgula'
    )

    class Meta:
        fields = ('channel',)

django/hub/projects/views.py
# coding: utf-8
import logging

from urlparse import urljoin

from django.conf import settings
from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import (CreateView, UpdateView, BaseFormView,
                                       DeleteView)

from forms import (
    ProjectForm,
    ChangelogForm,
    SendMailChangelogForm,
    SendSlackForm
)
from models import Project, Changelog


logger = logging.getLogger('projects.views')


class ProjectListView(ListView):
    queryset = Project.objects.order_by('name')
    template_name = 'projects/project_list.html'

    def get_queryset(self):
        return super(ProjectListView, self).get_queryset().filter(parent=None)


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects/project_detail.html'
    slug_field = 'name'

    def get_initial(self):
        last_changelog = self.project.changelog_set.order_by('-id').first()

        if last_changelog:
            email_recipients = last_changelog.email_recipients
        else:
            email_recipients = ', '.join(settings.DEFAULT_CHANGELOG_RECIPIENTS)

        return {
            'email_recipients': email_recipients,
            'email_subject': u'Changelog - {}'.format(self.project.name),
            'channel': '#changelogs',
        }

    def get_form_kwargs(self):
        return {'initial': self.get_initial()}

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        self.project = self.object
        form_kwargs = self.get_form_kwargs()
        context['send_mail_form'] = SendMailChangelogForm(**form_kwargs)
        context['send_slack_form'] = SendSlackForm(**form_kwargs)
        return context


class ProjectUpdateView(UpdateView):
    form_class = ProjectForm
    template_name = 'projects/project_form.html'

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return Project.objects.all()
        return Project.objects.filter(team=self.request.user.team)

    def get_success_url(self):
        return reverse('projects:project_detail', args=(self.get_object().id,))


class ProjectCreateView(CreateView):
    form_class = ProjectForm
    template_name = 'projects/project_form.html'

    def form_valid(self, form):
        project = form.save(commit=False)
        project.added_by = self.request.user
        project.save()
        form.save_m2m()

        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={'pk': project.pk})
        )

    def get_initial(self):
        return {
            'parent': self.kwargs.get('project_pk')
        }


class ChangelogCreateView(CreateView):
    form_class = ChangelogForm
    model = Changelog

    def dispatch(self, *args, **kwargs):
        self.project = Project.objects.get(
            pk=kwargs['project_id'],
        )
        return super(ChangelogCreateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ChangelogCreateView, self).get_context_data(**kwargs)
        context['project'] = self.project
        return context

    def get_initial(self):
        last_changelog = self.project.changelog_set.order_by('-id').first()
        if last_changelog:
            email_recipients = last_changelog.email_recipients
        else:
            email_recipients = ', '.join(settings.DEFAULT_CHANGELOG_RECIPIENTS)

        return {
            'email_recipients': email_recipients,
            'email_subject': u'Changelog - {}'.format(self.project.name),
            'description': u'# Versão X.Y.Z\n\n* ...\n* ...'
        }

    def form_valid(self, form):
        changelog = form.save(commit=False)
        changelog.project = self.project
        changelog.added_by = self.request.user
        changelog.save()

        if form.cleaned_data['send_mail'] is True:
            changelog.send_mail()

        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={
                'pk': self.project.id,
            })
        )


class ChangelogUpdateView(UpdateView):
    model = Changelog
    form_class = ChangelogForm
    pk_url_kwarg = 'changelog_id'

    def dispatch(self, *args, **kwargs):
        self.changelog = get_object_or_404(
            Changelog,
            pk=kwargs['changelog_id'],
            email_sent=False,
        )
        return super(ChangelogUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        changelog = form.save(commit=False)
        changelog.added_by = self.request.user
        changelog.save()

        if form.cleaned_data['send_mail'] is True:
            changelog.send_mail()

        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={
                'pk': self.changelog.project.id,
            })
        )

    def get_context_data(self, **kwargs):
        context = super(ChangelogUpdateView, self).get_context_data(**kwargs)
        context['project'] = self.object.project
        return context


class ChangelogDeleteView(DeleteView):
    form_class = ChangelogForm
    pk_url_kwarg = 'changelog_id'
    http_method_names = ['post', 'delete']
    queryset = Changelog.objects.filter(email_sent=False)

    def get_success_url(self):
        return reverse('projects:project_detail', kwargs={
            'pk': self.object.project_id,
        })


class ChangelogSendMailView(BaseFormView):
    form_class = SendMailChangelogForm
    http_method_names = ['post', ]

    def dispatch(self, *args, **kwargs):
        self.changelog = get_object_or_404(
            Changelog,
            pk=kwargs['changelog_id'],
        )
        return super(ChangelogSendMailView, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ChangelogSendMailView, self).get_form_kwargs()
        kwargs['instance'] = self.changelog
        return kwargs

    def form_valid(self, form):
        changelog = form.save(commit=False)
        changelog.added_by = self.request.user
        changelog.save()
        changelog.send_mail()

        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={
                'pk': self.changelog.project.id,
            })
        )

    def form_invalid(self, form):
        messages.error(
            self.request,
            u'Informações inválidas para enviar e-mail.'
        )
        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={
                'pk': self.changelog.project.id,
            })
        )


class ChangelogSendSlackView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('changelog_id')
        changelog = get_object_or_404(Changelog, pk=pk)

        channels = request.POST.get('channel', '#changelogs').split(',')

        for channel in channels:
            channel = channel.strip()
            kwargs = {
                'channel': channel,
                'username': request.user.name,
                'text': u'{}\n{}'.format(
                    changelog.project,
                    changelog.description
                ), 'icon_emoji': ':memo:',
            }

            try:
                changelog.send_slack(**kwargs)
            except Exception as e:
                logger.exception(u'Failed to send changelog')
                logger.exception(e, exc_info=True)

        return HttpResponseRedirect(
            reverse('projects:project_detail', kwargs={
                'pk': changelog.project.id,
            })
        )

django/hub/projects/templates/projects/changelog_email.html
{% load thumbnail %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <style>
            .img-circle {
              border-radius: 50%;
            }
        </style>
    </head>
    <body>
        <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">
            <tr>
                <td align="center" valign="top">
                    <table border="0" cellpadding="20" cellspacing="0" width="650" id="emailContainer">
                        <tr>
                            <td colspan="2" align="center" valign="top" style="padding-bottom:0">
                                <img src="http://hub.luizalabs.com/static/img/email_header.png">

                            </td>


                        </tr>

                        <tr>
                            {% if changelog.project.image %}
                                <td style="width: 100px">
                                    <img height="90" width="90" src="http://hub.luizalabs.com{{ changelog.project.image|thumbnail_url:'project' }}" class="img-circle img-responsive">
                                </td>
                            {% endif %}

                            <td style="padding-top:5px">
                                <p style="font-family:helvetica,sans-serif;color:#777;font-size:17px">
                                    <b>{{ changelog.project.name }}</b>
                                </p>

                                <p style="font-family:helvetica,sans-serif;color:#777;font-size:14px">

                                {% if changelog.project.team %}
                                    <a style="color:777" href="http://hub.luizalabs.com{% url 'teams:team_detail' changelog.project.team.id %}">{{ changelog.project.team }}</a><br/>
                                    Equipe: {% for m in changelog.project.team.account_set.all %}{% if forloop.last %}{% if not forloop.first %} e {% endif %}{% endif %}<a style="color:777" href="http://hub.luizalabs.com{% url 'accounts:account_detail' m.email %}">{{ m.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}<br/>
                                {% endif %}

                            </p>
                        </tr>

                        <tr>
                            <td  colspan="2"  style="padding-top:5px">


                                                        <p style="font-family:helvetica,sans-serif;color:#777">

                                {{ changelog.render_description|safe }}

                            </p>
                        </tr>

                    </table>

                    <table border="0" cellpadding="20" cellspacing="0" width="650" id="emailContainer">
                        <tr>
                            <td align="center" valign="top">
                                <a href="http://hub.luizalabs.com">
                                <img src="http://hub.luizalabs.com/static/img/email_footer.png">
                                </a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

django/hub/projects/templates/projects/changelog_form.html
{% extends "base.html" %}
{% load bootstrap staticfiles %}

{% block tab_name %}projects{% endblock %}

{% block extra_js %}
    <script src="{% static "js/view/changelog.js" %}"></script>
    <script src="{% static "js/markdown.js" %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <span><a href="{% url 'projects:project_detail' project.pk %}">{{ project.name }}</a></span> <span class="hub-light-gray"><i class="glyphicon glyphicon-menu-right"></i></span>
            <h2 class="project-name">{% if object.pk %}Editar{% else %}Adicionar{% endif %} changelog: {{ changelog.project.name }}</h2>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|bootstrap }}
                <div class="pull-right">
                    <button type="button" class="btn btn-info" id="btn-preview" data-toggle="modal" data-target="#markdownPreview"><span class="glyphicon glyphicon-eye-open"></span> Preview</button>
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> {% if object.pk %}Salvar{% else %}Adicionar{% endif %}</button>
                </div>
            </form>
            {% if object and not object.email_sent %}
            <div class="pull-left">
                <form action="{% url 'projects:changelog_delete' object.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Apagar</button>
                </form>
            </div>
            {% endif %}
        </div>

        <div id="markdownPreview" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Preview Changelog</h4>
                    </div>
                    <div id="preview" class="modal-body"></div>
            </div>
            </div>
        </div>
    </div>

{% endblock %}

django/hub/projects/templates/projects/member_snippet.html
{% load thumbnail bootstrap staticfiles %}

<li>
    <a href="{% url 'accounts:account_detail' member.email %}" data-toggle="tooltip" data-placement="top" title="{{ member }}">
        <img height="35" width="35" src="{{ member.image|thumbnail_url:'person' }}" class="img-circle">
    </a>
</li>

django/hub/projects/templates/projects/project_card_snippet.html
<div class="col-sm-6 col-md-4 col-lg-3">
	<div class="panel panel-default card">
		<div class="panel-heading">
			<h4><a href="{% url 'projects:project_detail' child.pk %}"><strong>{{child.name}}</strong></a>
				<a href="{% url 'projects:project_update' child.id %}" class="btn btn-sm btn-default pull-right"><i class="glyphicon glyphicon-pencil"></i></a>
			</h4>
		</div>
		<div class="panel-body">
			<p>{{child.description}}</p>

			<ul class="list-unstyled list-inline">
                {% if child.repo_id %}
				    <li><a href="{{child.github}}"><i class="glyphicon glyphicon-link"></i> GitHub</a></li>
                {% endif %}
				<li><a href="{% url 'projects:project_detail' child.pk %}#changelogs"><i class="glyphicon glyphicon-hdd"></i> Changelog</a></li>
			</ul>

			<ul class="list-unstyled list-inline">

				{% for tag in child.tags.all %}
					<a href="{% url 'core:tags_list' tag.id %}" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-tag"></i> {{ tag.name }}</a>
				{% endfor %}
			</ul>
			<hr>
			<ul class="list-unstyled list-inline">
                {% if child.members.all %}
				{% for member in child.members.all %}
                    {% include 'projects/member_snippet.html' %}
				{% endfor %}
                {% endif %}
			</ul>
		</div>
	</div>
</div>

django/hub/projects/templates/projects/project_detail.html
{% extends "base.html" %}
{% load thumbnail bootstrap staticfiles %}

{% block tab_name %}projects{% endblock %}

{% block extra_js %}
    <script>
      var SEND_CHANGELOG_MAIL_URL = "{% url "projects:changelog_send_mail" 0 %}";
      var SEND_CHANGELOG_SLACK_URL = "{% url "projects:changelog_send_slack" 0 %}";
      var CHANGELOG_UPDATE_URL = "{% url "projects:changelog_update" 0 %}";

      // init tooltip
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      });
    </script>
    <script src="{% static "js/view/project_detail.js" %}"></script>
{% endblock %}

{% if parent %}
<li><a href="{% url 'projects:project_detail' parent.pk %}">{{ parent.name }}</a></li>
{% endif %}
<!-- <li><a href="{% url 'projects:project_detail' product.pk %}">{{ product.name }}</a></li> -->

{% block content %}

    <div class="row">
        <div class="col-md-10">
            <div class="clearfix content-heading media">
                {% if project.image %}
                    <img height="70" width="70" src="{{ project.image|thumbnail_url:'project' }}" class="img-circle pull-left">
                {% endif %}

                {% if project.parent %}
                  <span class="project-breadcrumb">
                    <a href="{% url 'projects:project_detail' project.parent.pk %}">{{ project.parent.name }}</a> <span class="hub-light-gray"><i class="glyphicon glyphicon-menu-right"></i></span>
                  </span>
                {% endif %}
                <h2 class="project-name{% if project.parent %} application{% endif %}">
                    {{ project.name }}
                    {% if project.team == user.team or user.is_superuser %}
                        <a class="btn btn-sm btn-default" href="{% url 'projects:project_update' project.id %}"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                    {% endif %}
                </h2>

                <p class="text-muted">{{ project.headline }}</p>

            </div>
        </div>
    </div>
    <hr>


    <div class="row">
        <div class="col-md-10">
            <table class="table table-bordered">
                {% if project.repo_id %}
                    <tr>
                        <td class="col-md-2">Repo</td>
                        <td class="col-md-10">
                            <a href="{{ project.github }}">{{ project.github }}</a>
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <td class="col-md-2">Tags</td>
                    <td class="col-md-10">
                        {% for tag in project.tags.all %}
                            <a href={% url 'core:tags_list' tag.id %} class="btn btn-default">{{ tag.name }}</a>
                        {% empty %}
                            <i>-</i>
                        {% endfor %}
                    </td>
                </tr>

                {% if project.team %}
                <tr>
                    <td class="col-md-2">Mantido pelo time</td>
                    <td class="col-md-10"><a href="{% url 'teams:team_detail' project.team.id %}">{{ project.team }}</a></td>
                </tr>
                {% endif %}

                <tr>
                    <td class="col-md-2">Passaram por este projeto</td>
                    <td class="col-md-10">
                        {% if project.members.all %}
                        <ul class="list-unstyled list-inline">
                        {% for member in project.members.all %}
                            {% include 'projects/member_snippet.html'%}
                        {% endfor %}
                        {% endif %}
                        </ul>
                    </td>
                </tr>

            </table>
            <hr>

            <div>
                {{ project.render_description|safe }}
            </div>

            <hr>

            {% if not project.parent_id %}
            <div class="row">
                <div class="col-sm-12">
                    <h3>
                        Aplicações <a class="btn btn-sm btn-default" href="{% url 'projects:child_project_create' project.id %}"><i class="glyphicon glyphicon-plus"></i> Adicionar</a>
                    </h3>
                    <br>
                    {% for child in project.applications.all %}
                        {% include 'projects/project_card_snippet.html' %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}

            <div class="row">
                <div class="col-sm-12">
                    <h3 id="changelogs">Changelog {% if not project.parent %}do produto{% endif %} <a class="btn btn-sm btn-default" href="{% url 'projects:changelog_add' project.id %}"><i class="glyphicon glyphicon-plus"></i> Adicionar</a></h3>
                    <br>
                    {% for cl in project.changelogs %}
                    <blockquote>
                        <div rel="{{ cl.pk }}" class="changelog-box {% if cl.email_sent %} no-edit{% endif %}">
                            <span class="hub-light-gray">{{ cl.created_at }}</span><br />
                            <span class="hub-light-gray"><strong>{% if cl.project.parent %}Aplicação{% else %}Produto{% endif %} {{ cl.project.name }}</strong></span>
                            <div class="changelog-container">
                                {{ cl.render_description|safe }}
                                {% if cl.last_slack_payload %}
                                    {% with reactions=cl.reactions %}
                                    <div class="thumbs text-muted" rel="{{ cl.pk }}">
                                        <span class="thumbs-up-count">
                                            {% if reactions.thumbs_up_count %}{{ reactions.thumbs_up_count }}{% else %}0{% endif %}
                                        </span>
                                        <span class="glyphicon glyphicon-thumbs-up"></span>
                                        <span class="thumbs-down-count">{% if reactions.thumbs_down_count %}{{ reactions.thumbs_down_count }}{% else %}0{% endif %}</span>
                                        <span class="glyphicon glyphicon-thumbs-down"></span>
                                    </div>
                                {% endwith %}
                                {% endif %}
                            </div>
                            <div class="actions hub-light-gray">
                                {% if not cl.email_sent %}
                                <span class="send-mail" rel="{{ cl.pk }}"><span class="glyphicon glyphicon-envelope"></span> Enviar e-mail</span> |
                                {% endif %}
                                <span class="send-slack" rel="{{ cl.pk }}"> <span class="glyphicon glyphicon-comment"></span> Enviar por slack</span>
                            </div>
                        </div>
                    </blockquote>
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>

    <div id="modal-mail" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Enviar changelog por e-mail</h4>
                </div>
                <form id="send_mail_changelog" role="form" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">{{ send_mail_form|bootstrap }}</div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="modal-slack" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Enviar changelog para o Slack</h4>
                </div>
                <form id="send_slack_changelog" role="form" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">{{ send_slack_form|bootstrap }}</div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

django/hub/projects/templates/projects/project_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block tab_name %}projects{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>{% if object.pk %}Atualizar {% if object.parent %}aplicação{% else %}produto{% endif %}: {{ object }}{% else %}Adicionar produto/aplicação{% endif %}</h2>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-md-6">
            {% if form.errors %}
            <div class="alert alert-danger">
                {{form.errors}}
            </div>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        {% if object.pk %}Atualizar{% else %}Adicionar{% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}