django/hub/accounts/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.AccountListView.as_view(), name='account_list'),
    url(
        r'^organogram/$',
        views.OrganogramView.as_view(),
        name='organogram'
    ),
    url(
        r'^(?P<slug>.*)/update/$',
        views.AccountUpdateView.as_view(),
        name='account_update'
    ),
    url(
        r'^(?P<slug>.*)/add-award/$',
        views.AccountAwardCreateView.as_view(),
        name='account_award_add'
    ),
    url(
        r'^(?P<slug>.*)/$',
        views.AccountDetailView.as_view(),
        name='account_detail'
    )
)

django/hub/core/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^tags/(?P<tag_id>\d+)/$', views.TagsListView.as_view(), name='tags_list'),
    url(r'^get_tags_json/$', views.get_tags_json, name='get_tags_json'),
)

django/hub/projects/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^add/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^(?P<project_pk>\d+)/applications/add/$',
        views.ProjectCreateView.as_view(),
        name='child_project_create'),
    url(r'^(?P<pk>\d+)/$',
        views.ProjectDetailView.as_view(),
        name='project_detail'),
    url(
        r'^(?P<pk>\d+)/update/$',
        views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(
        r'^(?P<project_id>\d+)/changelog/add/$',
        views.ChangelogCreateView.as_view(),
        name='changelog_add'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/update/$',
        views.ChangelogUpdateView.as_view(),
        name='changelog_update'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/delete/$',
        views.ChangelogDeleteView.as_view(),
        name='changelog_delete'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_mail/$',
        views.ChangelogSendMailView.as_view(),
        name='changelog_send_mail'
    ),
    url(
        r'^changelog/(?P<changelog_id>\d+)/send_slack/$',
        views.ChangelogSendSlackView.as_view(),
        name='changelog_send_slack'
    ),
)

django/hub/teams/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.TeamListView.as_view(), name='team_list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
    url(r'^add/$', views.TeamCreateView.as_view(), name='team_create'),
)

django/hub/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from news.models import Entry


admin.autodiscover()


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['news_entries'] = Entry.objects.order_by('-created_at')
        return context


class ProjectsRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return '/products/{}'.format(self.kwargs.get('pattern', ''))


urlpatterns = patterns(
    '',
    url('^$', HomeView.as_view(), name='home'),
    url(r'^login/$', TemplateView.as_view(template_name='login.html')),
    url(r'^mgr/', include(admin.site.urls)),
    url(r'^projects/(?P<pattern>.*?)$', ProjectsRedirectView.as_view()),

    # third party
    (r'^accounts/', include('allauth.urls')),

    # local apps
    (r'^pr/', include('pr.urls', namespace='pr')),
    (r'^people/', include('accounts.urls', namespace='accounts')),
    (r'^teams/', include('teams.urls', namespace='teams')),
    (r'^products/', include('projects.urls', namespace='projects')),
    (r'^', include('core.urls', namespace='core')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/hub/accounts/models.py
# coding: utf-8
import logging
from dateutil import relativedelta
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.timezone import now
from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager
from teams.models import Team
from utils.softdelete import SoftDeleteMixin


logger = logging.getLogger('accounts.models')


class CompanyBranch(models.Model, SoftDeleteMixin):
    name = models.CharField(u'nome', max_length=32)

    def __unicode__(self):
        return self.name


class ActiveUserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email=email, password=password)
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user

    def get_queryset(self, *args, **kwargs):
        return super(ActiveUserManager, self) \
            .get_queryset(*args, **kwargs).filter(leaving_date__isnull=True)


class Account(MPTTModel, AbstractBaseUser, PermissionsMixin):

    """
    An account represents an employee
    """
    USERNAME_FIELD = 'email'

    reports_to = TreeForeignKey(
        'self', null=True, blank=True,
        related_name='account_set', verbose_name=u'líder direto',
    )
    branch = models.ForeignKey(
        CompanyBranch, max_length=16, null=True,
        verbose_name=u'filial'
    )
    team = models.ForeignKey(Team, null=True, blank=True, verbose_name=u'time')
    name = models.CharField(u'nome', max_length=128)

    phone = models.CharField(u'telefone', max_length=32, blank=True)
    github_username = models.CharField(u'Github (pessoal)', max_length=50, blank=True)
    twitter_username = models.CharField(u'Twitter', max_length=50, blank=True)

    image = models.ImageField(
        u'foto', upload_to='accounts/', blank=True,
        help_text=u'Escolha uma foto real e atual, para que seja identificado - ex.: não coloque a foto do Darth Vader. Envie imagens quadradas (mínimo 150x150px).',
    )

    # auth
    email = models.EmailField(u'e-mail', max_length=128, unique=True)

    created_at = models.DateTimeField(default=now)

    birth_date = models.DateField(u'data de aniversário', null=True, blank=True)
    starting_date = models.DateField(u'data de admissão', null=True, blank=True)
    leaving_date = models.DateField(u'data de demissão', null=True, blank=True)

    tags = TaggableManager(verbose_name=u'tags')

    objects = ActiveUserManager()
    all_objects = models.Manager()

    class MPTTMeta:
        parent_attr = 'reports_to'
        order_insertion_by = ['name']

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name or self.email

    def delete(self, *args, **kwargs):
        """
        Soft delete will not work due to MPTT implementation.
        Set `leaving_date` to a valid date and the account will not
        appear anymore.
        """
        raise Exception('An account cannot be deleted, set `leaving_date` instead')

    def is_staff(self):
        return self.is_staff

    def has_filled_profile(self):
        for attr in ('github_username', 'branch', 'phone', 'image'):
            if not getattr(self, attr):
                return False
        return True

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def get_contrib_period(self):
        return relativedelta.relativedelta(
            self.leaving_date or now().date(),
            self.starting_date
        )

django/hub/projects/models.py
# coding: utf-8
import json
import logging
import urllib

import markdown
import requests

from django.conf import settings
from django.db import models
from django.utils.timezone import now

from taggit.managers import TaggableManager

from accounts.models import Account
from teams.models import Team
from utils import notify
from utils.email import send_email_template
from utils.softdelete import SoftDeleteManager, SoftDeleteMixin


logger = logging.getLogger('projects.models')


class Project(models.Model, SoftDeleteMixin):
    parent = models.ForeignKey('self', related_name='applications',
                           null=True, blank=True, verbose_name='Produto')
    name = models.CharField(u'nome', max_length=32)
    headline = models.CharField(u'headline', max_length=64, blank=True,
                                help_text=u'Ex.: "Plataforma de recomendações"')
    description = models.TextField(u'descrição', help_text=u'Utilize formatação Markdown')

    team = models.ForeignKey(Team, null=True, blank=True, verbose_name=u'time mantenedor')
    added_by = models.ForeignKey(Account, related_name='added_projects')
    members = models.ManyToManyField(Account, null=True, blank=True,
                                     verbose_name=u'pessoas que passaram pelo projeto')

    repo_id = models.CharField(u'repositório Github (org/repo_name)', blank=True, max_length=32,
                               help_text=u'Inclua a organização, exemplo: "luizalabs/p36"')
    travis_enabled = models.BooleanField(u'Incluir badge do Travis CI', default=False)

    image = models.ImageField(
        u'logotipo', upload_to='projects/', blank=True,
        help_text=u'Todo projeto precisa de um logotipo! Envie imagens quadradas (~500x500px)',
    )
    created_at = models.DateTimeField(default=now)
    tags = TaggableManager(verbose_name=u'tags')

    def __unicode__(self):
        return self.name

    @property
    def github(self):
        return 'https://github.com/{}'.format(self.repo_id)

    def render_description(self):
        return markdown.markdown(self.description)

    @property
    def changelogs(self):
        if not self.parent:
            return Changelog.objects.filter(
                models.Q(project=self) |
                models.Q(project__in=self.applications.all())
            )
        return self.changelog_set.all()


class Changelog(models.Model, SoftDeleteMixin):
    project = models.ForeignKey(Project)
    email_recipients = models.TextField(u'Destinatários', blank=True,
                                        help_text='Separe os e-mails por vírgula')
    email_subject = models.CharField(u'assunto do e-mail', max_length=64, blank=True,
                                     help_text=u'Ex.: "Changelog - Stewie - Sprint 3"')

    description = models.TextField(u'descrição', help_text=u'Escreva em português. Utilize formatação Markdown.')

    added_by = models.ForeignKey(Account, related_name='added_changelogs')
    created_at = models.DateTimeField(default=now)
    email_sent = models.BooleanField(u'e-mail enviado', default=False)
    last_slack_payload = models.CharField(u'última mensagem para o slack',
                                          max_length=512, blank=True,
                                          null=True)

    class Meta:
        ordering = ('-id',)

    def __unicode__(self):
        return self.email_subject

    def render_description(self):
        return markdown.markdown(self.description)

    def send_mail(self):
        if self.email_sent is False:
            send_email_template(
                subject=self.email_subject,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[e.strip() for e in
                                self.email_recipients.split(',')],
                template='projects/changelog_email.html',
                context={
                    'changelog': self,
                }
            )
            self.email_sent = True
            self.save()

    def send_slack(self, **kwargs):
        self.last_slack_payload = notify.slack(**kwargs)
        self.save()

    @property
    def reactions(self):
        slack_info = json.loads(self.last_slack_payload)
        slack_info['token'] = settings.CHANGELOG_API_TOKEN

        get_reactions_url = u'https://slack.com/api/reactions.get?{}'
        reactions = requests.get(get_reactions_url.format(
            urllib.urlencode(slack_info)
        ))
        reactions = json.loads(reactions.text)
        reactions = reactions.get('message', {}).get('reactions', [])
        data = {}
        for reaction in reactions:
            if reaction['name'] == '+1':
                data['thumbs_up_count'] = reaction['count']
            elif reaction['name'] == '-1':
                data['thumbs_down_count'] = reaction['count']
        return data

django/hub/accounts/forms.py
# coding: utf-8

from django import forms

from models import Account
from utils.cleantags import CleanTagsMixin


class ProfileUpdateForm(CleanTagsMixin, forms.ModelForm):
    reports_to = forms.ModelChoiceField(
        queryset=Account.objects.all(),
        empty_label='-' * 8,
        required=False,
    )

    birth_date = forms.DateField(
        label=u'Data de Aniversário',
        input_formats=['%d/%M/%Y'],
        help_text=u'Ex: 20/10/1990'
    )

    class Meta:
        fields = ('reports_to', 'team', 'name', 'birth_date', 'branch', 'phone',
                  'github_username', 'twitter_username', 'image', 'tags',
                  'starting_date', 'leaving_date')
        model = Account

    def __init__(self, request, *args, **kwargs):
        ret = super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        if not request.user.is_superuser:
            del self.fields['starting_date']
            del self.fields['leaving_date']
        return ret

    def clean_reports_to(self):
        if self.cleaned_data['reports_to'] == self.instance:
            raise forms.ValidationError(u'Mas só pode estar de brincanagem! Você não pode ser seu próprio chefe!')
        return self.cleaned_data['reports_to']

django/hub/accounts/views.py
# coding: utf-8
import logging

from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import (
    CreateView, DetailView, ListView, TemplateView, UpdateView
)

from awards.forms import AccountAwardForm

from forms import ProfileUpdateForm
from models import Account


logger = logging.getLogger('accounts.views')


class AccountListView(ListView):
    queryset = Account.objects.order_by('name')
    template_name = 'accounts/account_list.html'


class AccountDetailView(DetailView):
    model = Account
    template_name = 'accounts/account_detail.html'
    slug_field = 'email'

    def get_context_data(self, **kwargs):
        context = super(AccountDetailView, self).get_context_data(**kwargs)
        context['user_is_ancestor'] = self.request.user.is_ancestor_of(self.get_object())
        return context


class AccountUpdateView(UpdateView):
    model = Account
    form_class = ProfileUpdateForm
    template_name = 'accounts/account_update.html'
    slug_field = 'email'
    success_url = reverse_lazy('accounts:account_list')

    def get_queryset(self):
        qs = super(AccountUpdateView, self).get_queryset()

        if not self.request.user.is_superuser:
            qs = qs.filter(email__exact=self.request.user.email)
        return qs

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = super(AccountUpdateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class OrganogramView(TemplateView):
    template_name = 'accounts/organogram.html'

    def get_context_data(self, **kwargs):
        context = super(OrganogramView, self).get_context_data(**kwargs)
        context['people'] = Account.objects.order_by('name')
        return context


class AccountAwardCreateView(CreateView):
    form_class = AccountAwardForm
    template_name = 'awards/account_award_add.html'
    slug_field = 'email'

    def dispatch(self, *args, **kwargs):
        self.account = Account.objects.get(
            email=kwargs['slug'],
        )
        return super(AccountAwardCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        award = form.save(commit=False)
        award.account = self.account
        award.awarded_by = self.request.user
        award.save()

        return HttpResponseRedirect(
            reverse('accounts:account_detail', kwargs={
                'slug': self.account.email,
            })
        )

django/hub/accounts/templates/accounts/account_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="clearfix content-heading media">
                {% if account.image %}
                    <img height="70" width="70" src="{{ account.image|thumbnail_url:'person_large' }}" class="img-circle pull-left">
                {% endif %}

                <h2>
                    {{ account.name }}
                    {% if account == user or user.is_superuser %}
                        <a class="btn btn-sm btn-default" href="{% url 'accounts:account_update' account.email %}"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                    {% endif %}
                </h2>
            </div>
        </div>
    </div>
    <hr>

        <div class="row">
            <div class="col-md-10">
                <table class="table table-bordered">
                    <tr>
                        <td class="col-md-2">E-mail</td>
                        <td class="col-md-10">{{ account.email }}</td>
                    </tr>
                    <tr>
                        <td class="col-md-2">Tags</td>
                        <td class="col-md-10">
                            {% for tag in account.tags.all %}
                                <a href={% url 'core:tags_list' tag.id %} class="btn btn-default">{{ tag.name }}</a>
                            {% empty %}
                                <i>-</i>
                            {% endfor %}
                        </td>
                    </tr>
                    {% if account.team %}
                    <tr>
                        <td class="col-md-2">Time</td>
                        <td class="col-md-10"><a href="{% url 'teams:team_detail' account.team.id %}">{{ account.team }}</a></td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="col-md-2">Projetos</td>
                        <td class="col-md-10">
                            {% for project in account.project_set.all %}
                                <a href="{% url 'projects:project_detail' project.id %}"><img height="35" width="35" src="{{ project.image|thumbnail_url:'person' }}" class="img-circle"> {{ project }}</a>&nbsp;
                            {% empty %}
                                -
                            {% endfor %}
                        </td>
                    </tr>

                    {% if account.github_username %}
                    <tr>
                        <td>Github (pessoal)</td>
                        <td>
                            <a target="_blank" href="https://github.com/{{ account.github_username }}">
                                {{ account.github_username }}
                            </a>
                        </td>
                    </tr>
                    {% endif %}

                    {% if account.twitter_username %}
                    <tr>
                        <td>Twitter</td>
                        <td>
                            <a target="_blank" href="https://twitter.com/{{ account.twitter_username }}">
                                {{ account.twitter_username }}
                            </a>
                        </td>
                    </tr>
                    {% endif %}

                    {% if object.awards.count > 0 %}
                    <tr>
                        <td class="col-md-2">Prêmios</td>
                        <td class="col-md-10">
                            {% for award in object.awards.all %}
                                <img height="50" width="50" src="{{ award.award.image.url }}" class="img-circle"> {{ award.title }}</a>&nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                    {% endif %}
                </table>


                {% if user.is_superuser or user_is_ancestor %}
                    <h4><i class="glyphicon glyphicon-lock"></i> Visível apenas para gestores</h4>
                    <table class="table table-bordered">

                        {% if account.starting_date %}
                            <tr>
                                <td class="col-md-2">Tempo de contribuição</td>
                                <td class="col-md-10">
                                    {% with account.get_contrib_period as dt %}
                                        {% if dt.years %}
                                            {{ dt.years }} ano{{ dt.years|pluralize }}
                                        {% endif %}

                                        {% if dt.months %}
                                            {{ dt.months }} mes{{ dt.months|pluralize:"es" }}
                                        {% endif %}

                                        {% if dt.days %}
                                            {{ dt.days }} dia{{ dt.days|pluralize }}
                                        {% endif %}
                                    {% endwith %}
                                </td>
                            </tr>
                        {% endif %}

                        <tr>
                            <td class="col-md-2">Data de admissão</td>
                            <td class="col-md-10">
                                {% if account.starting_date %}
                                    {{ account.starting_date|date:"d/m/Y" }}
                                {% else %}
    <a href="{% url 'accounts:account_update' account.email %}" style="color:red"><i class="glyphicon glyphicon-exclamation-sign"></i> Informação pendente</a>
                                {% endif %}

                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-2">Data de demissão</td>
                            <td class="col-md-10">{{ account.leaving_date|date:"d/m/Y"|default:"-" }}</td>
                        </tr>

                        <tr>
                            <td class="col-md-2">Premiar</td>
                            <td><a href="{% url 'accounts:account_award_add' account.email %}" class="btn btn-primary btn-success"><span class="glyphicon glyphicon-tower"></span> Premiar</a></td>
                        </tr>

                    </table>
                {% endif %}
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

django/hub/accounts/templates/accounts/account_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block tab_name %}people{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-10">
            <h2>Pessoas</h2>
        </div>
    </div>
    <hr>

    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Time</th>
                <th>Filial</th>
                <th>Telefone</th>
            </tr>
        </thead>

        {% for account in object_list %}
            <tr>
                <td><img height="25" width="25" src="{{ account.image|thumbnail_url:'person' }}" class="img-circle"> <a href="{% url 'accounts:account_detail' account.email %}">{{ account.name }}</a></td>
                <td>{{ account.team|default:"-" }}</td>
                <td>{{ account.branch|default:"-" }}</td>
                <td>{{ account.phone|default:"-" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

django/hub/accounts/templates/accounts/account_update.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h2>Atualizar perfil{% if user.is_superuser %}: {{ object }}{% endif %}</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>

            </form>
        </div>
    </div>

{% endblock %}

django/hub/accounts/templates/accounts/organogram.html
{% extends "base.html" %}
{% load mptt_tags %}

{% block content %}

    <ul>
        {% recursetree people %}
            <li>

                {% if node.is_root_node %}
                    <strong>{{ node.name }} {{ node.level }}</strong>
                {% else %}
                    {{ node.name }}
                {% endif %}

                {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                {% endif %}
            </li>
        {% endrecursetree %}
    </ul>

{% endblock content %}